### ISSUE TITLE
Amazon Echo Plus as gateway

### ISSUE THREAD

**Issue by Zabov79** [nidayand/node-red-contrib-tradfri#25] opened 2019-01-29 14:48 UTC
I would like to use my echo plus as gateway and create some flows in node red. Is it possible?

**Comment by SteveRMann** [comment] 2019-01-29 15:39
You are asking this in the wrong place.  An Amazon Echo device is not and can not be a gateway.  The Tradfri Gateway is a bridge between your local LAN and the Zigbee devices like the Tradfri lights.  

If you want to use Alexa with Node-Red, look at the Alexa Local node in the Node-Red Pallette Manager.

**Comment by Zabov79** [comment] 2019-01-29 17:05
I'm already using Alexa with node red to control a couple of sonoff switch but I'd like to control also Ikea Tradfri and Philips Hue bulbs that I have. The Echo Plus integrate a zigbee protocol to control Philips Hue and Ikea Tradfri lights without their specific gateway. So I was asking if it's possible to use echo plus as gateway for these bulbs inside a flow in node red

**Comment by SteveRMann** [comment] 2019-01-29 17:13
This is the first that I've heard that the Echo Plus is also a Zigbee gateway.

**Comment by nidayand** [comment] 2019-03-14 12:04
I guess that you are asking for event listeners to be implemented in the nodes so it can be triggered from Echo.. if so than this is a duplicate of #8

**Closed as completed by nidayand** 2019-03-14 12:04 UTC
